# Generated by Django 4.1.5 on 2023-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todos",
            name="deadline",
            field=models.DateTimeField(default="2023-01-29"),
            preserve_default=False,
        ),
    ]
